# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField(null=True)),
                ('date_received', models.DateTimeField(null=True)),
                ('date_sent', models.DateTimeField(null=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('latitude', models.FloatField(null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitud')),
                ('speed', models.FloatField(null=True, verbose_name='Velocidad')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, null=True)),
                ('imei', models.CharField(max_length=255, null=True, unique=True, verbose_name='Número de IMEI')),
                ('mail_drop_alarm', models.CharField(max_length=255, null=True)),
                ('modification_date', models.DateTimeField(null=True, verbose_name='Tiempo')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre Dispositivo')),
                ('phone_number', models.CharField(max_length=100, null=True, verbose_name='Número de SIM')),
                ('status', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField(null=True, verbose_name='Latitud')),
                ('lng', models.FloatField(null=True, verbose_name='Longitud')),
                ('time', models.DateTimeField(null=True, verbose_name='Tiempo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(null=True)),
                ('command', models.CharField(max_length=500, null=True)),
                ('sent_date', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField(null=True, verbose_name='Altitud')),
                ('battery', models.CharField(max_length=255, null=True)),
                ('command', models.CharField(max_length=255, null=True)),
                ('course', models.FloatField(null=True)),
                ('extended_info', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitud')),
                ('sent_date', models.DateTimeField(null=True)),
                ('speed', models.FloatField(null=True, verbose_name='Velocidad')),
                ('time', models.DateTimeField(null=True)),
                ('valid', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Positions_Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.FloatField(null=True, verbose_name='Altitud')),
                ('battery', models.CharField(max_length=255, null=True)),
                ('command', models.CharField(max_length=255, null=True)),
                ('course', models.FloatField(null=True)),
                ('extended_info', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True, verbose_name='Latitud')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitud')),
                ('sent_date', models.DateTimeField(null=True)),
                ('speed', models.FloatField(null=True, verbose_name='Velocidad')),
                ('time', models.DateTimeField(null=True)),
                ('valid', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Device')),
            ],
        ),
        migrations.AddField(
            model_name='alarm',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Device'),
        ),
    ]
