# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True, verbose_name='Tiempo')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('NUEVO', 'NUEVO'), ('EN_CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], max_length=20, verbose_name='Estado')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitud')),
                ('log', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitud')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
