# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20161015_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidente_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
