# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_auto_20161016_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('EN_CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], default='NUEVO', max_length=20, verbose_name='Estado'),
        ),
    ]
