# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_auto_20161016_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoincidente',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
