# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20161016_2005'),
        ('logistica', '0008_auto_20161016_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionIncidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tiempo')),
                ('estado', models.CharField(choices=[('NUEVO', 'NUEVO'), ('EN CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], default='NUEVO', max_length=20, verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('centro_emergencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.CentroEmergencia')),
            ],
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('EN CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], default='NUEVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='asignacionincidente',
            name='incidente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistica.Incidente'),
        ),
        migrations.AddField(
            model_name='asignacionincidente',
            name='vehiculos',
            field=models.ManyToManyField(to='servicios.Vehiculo'),
        ),
    ]
