# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_auto_20161016_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionincidente',
            name='estado',
            field=models.CharField(choices=[('EN CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], default='EN CURSO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('EN CURSO', 'EN CURSO (ASIGNADO)'), ('RESULTO', 'RESUELTO'), ('FINALIZADO', 'FINALIZADO')], default='NUEVO', max_length=20, verbose_name='Estado'),
        ),
    ]
