# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lng', models.FloatField(verbose_name='Longitud')),
                ('sector', models.CharField(choices=[('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO')], max_length=10, verbose_name='Sector')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Centros de emergencias',
                'verbose_name': 'Centro de emergencia',
            },
        ),
        migrations.CreateModel(
            name='TipoCentroEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Centro Emergencia',
                'verbose_name': 'Tipo Centro Emergencia',
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Vehiculos',
                'verbose_name': 'Tipo Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('nro_motor', models.CharField(max_length=100, verbose_name='N° Motor')),
                ('nro_chasis', models.CharField(max_length=100, verbose_name='N° Chasis')),
                ('sector', models.CharField(choices=[('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO')], max_length=20, verbose_name='Sector')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('gps_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gps.Device', verbose_name='GPS')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.TipoVehiculo', verbose_name='Tipo Vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'verbose_name': 'Vehiculo',
            },
        ),
        migrations.AddField(
            model_name='centroemergencia',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.TipoCentroEmergencia', verbose_name='Tipo Vehiculo'),
        ),
    ]
