# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20161107_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descripción'),
        ),
    ]
