# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20161016_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroemergencia',
            name='nivel',
            field=models.CharField(choices=[('NINGUNO', 'NINGUNO'), ('PRIMERO', 'PRIMERO'), ('SEGUNDO', 'SEGUNDO'), ('TERCERO', 'TERCERO')], max_length=10, verbose_name='Nivel'),
        ),
    ]
